name: B Only

on:
  push:
    branches:
      - main
    paths:
      - "b/**"
jobs:
  change-job:
    runs-on: ubuntu-latest
    outputs:
      has_other_changes: ${{steps.other-changes.outputs.changed}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: other-changes
        with:
          paths: ":!b*"

  echo-job:
    needs: change-job
    runs-on: ubuntu-latest
    if: needs.change-job.outputs.has_other_changes != 'true'
    steps:
      - name: Echo for b
        run: echo "hello from B"
